version: "3.7"
services:
  search:
    image: search
    deploy:
      replicas: 2
    ports:
      - "3000:3000"
    networks:
      - app-network
  auth:
    image: auth
    ports:
      - "3001:3000"
    networks:
      - app-network
  booking:
    image: booking
    ports:
      - "3002:3000"
    networks:
      - app-network

networks:
  app-network:
    external: true
