apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
  labels:
    app: search
spec:
  selector:
    matchLabels:
      app: search
  replicas: 2
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: mhnatyshyn/search-please
      hostNetwork: true

---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search
  ports:
    - name: http
      port: 3000
      nodePort: 30080
  type: NodePort
